version: '3.8'

services:
  httpalu:
    image: ghcr.io/yanorei32/http-alu:latest@sha256:82aded96ffef37cc9c2d71afa66726577fde9648455346c435c8433273a327c8
    hostname: httpalu
    container_name: httpalu__httpalu
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 256m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.5.1@sha256:a5b5e6fd9a372f054b9a843c219bfbcdceb54691605312a8b1ee72978bdf1aa1
    hostname: cloudflared
    container_name: httpalu__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: httpalu__default
