version: '3.8'

services:
  httpalu:
    image: ghcr.io/yanorei32/http-alu:latest@sha256:ea5aa7c31f46aede4db5a873cdd2efea44faa982d3491176f40b7c0adc8a1d72
    hostname: httpalu
    container_name: httpalu__httpalu
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 256m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.7.2@sha256:4f6655284ab3d252b7f28fedb19fe6c8fc82ee5b1295c20ac74d475e5398a52d
    hostname: cloudflared
    container_name: httpalu__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: httpalu__default
