version: '3.8'

services:
  httpalu:
    image: ghcr.io/yanorei32/http-alu:latest@sha256:50f9917fdee68b7d838a23f70eced2f295ae27c4aaa1aecb0acd8b3e6c7def68
    hostname: httpalu
    container_name: httpalu__httpalu
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 256m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.6.1@sha256:6d91c121b803126f7a5344005d17a9324788fc09d305b6e2560ec6040a7ae283
    hostname: cloudflared
    container_name: httpalu__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: httpalu__default
